  title: "Projeto de Previsão de Vendas Rossmann"
  image: "images/rossmann.jpg"
  link: "https://github.com/f-mtz/rossmann-sales-predict"
  description: |
    Modelo de previsão de vendas automatizado para a rede de farmácias Rossmann,
    reduzindo a dependência de previsões manuais.
  show: true
  topics:
    - "Previsão de séries temporais"
    - "Feature engineering"
    - "Validação cruzada temporal"
  tools:
    - "Python 3.11 e Pyenv"
    - "Pandas e Numpy"
    - "XGBoost"
    - "Flask e Streamlit"